# -*- coding: utf-8 -*-
"""
This family file was auto-generated by $Id: b4675f8c1426906ff25dbf5dc703facd391360da $
Configuration parameters:
  url = http://wiki.teamliquid.net/starcraft2
  name = starcraft2

Please do not commit this to the Git repository!
"""

from pywikibot import family
from pywikibot.tools import deprecated


class Family(family.Family):
    def __init__(self):
        family.Family.__init__(self)
        self.name = 'liquipedia'
        self.langs = {
            'commons': 'wiki.teamliquid.net',
            'counterstrike': 'wiki.teamliquid.net',
            'dota2': 'wiki.teamliquid.net',
            'hearthstone': 'wiki.teamliquid.net',
            'heroes': 'wiki.teamliquid.net',
            'overwatch': 'wiki.teamliquid.net',
            'smash': 'wiki.teamliquid.net',
            'staff': 'wiki.teamliquid.net',
            'starcraft': 'wiki.teamliquid.net',
            'starcraft2': 'wiki.teamliquid.net',
            'warcraft': 'wiki.teamliquid.net',
            'fighters': 'wiki.teamliquid.net',
            'rocketleague': 'wiki.teamliquid.net',
            'clashroyale': 'wiki.teamliquid.net',
            'crossfire': 'wiki.teamliquid.net',
            'trackmania': 'wiki.teamliquid.net',
            'battlerite': 'wiki.teamliquid.net',
            'diabotical': 'wiki.teamliquid.net',
            'teamfortress': 'wiki.teamliquid.net',
            'leagueoflegends': 'wiki.teamliquid.net',
            'worldofwarcraft': 'wiki.teamliquid.net',
            'fifa': 'wiki.teamliquid.net',
            'pokemon': 'wiki.teamliquid.net',
            'projectx': 'wiki.teamliquid.net',
            'quake': 'wiki.teamliquid.net',
            'rainbowsix': 'wiki.teamliquid.net',
            'focommons': 'wiki.liquipedia.space',
            'fodota2': 'wiki.liquipedia.space',
            'fooverwatch': 'wiki.liquipedia.space',
            'fostarcraft': 'wiki.liquipedia.space',
            'fostarcraft2': 'wiki.liquipedia.space',
            'fowarcraft': 'wiki.liquipedia.space',
        }

    def scriptpath(self, code):
        return {
            'commons': '/commons',
            'counterstrike': '/counterstrike',
            'dota2': '/dota2',
            'hearthstone': '/hearthstone',
            'heroes': '/heroes',
            'overwatch': '/overwatch',
            'smash': '/smash',
            'staff': '/staff',
            'starcraft': '/starcraft',
            'starcraft2': '/starcraft2',
            'warcraft': '/warcraft',
            'fighters': '/fighters',
            'rocketleague': '/rocketleague',
            'clashroyale': '/clashroyale',
            'crossfire': '/crossfire',
            'trackmania': '/trackmania',
            'battlerite': '/battlerite',
            'diabotical': '/diabotical',
            'teamfortress': '/teamfortress',
            'leagueoflegends': '/leagueoflegends',
            'worldofwarcraft': '/worldofwarcraft',
            'fifa': '/fifa',
            'pokemon': '/pokemon',
            'projectx': '/projectx',
            'quake': '/quake',
            'rainbowsix': '/rainbowsix',
            'focommons': '/commons',
            'fodota2': '/dota2',
            'fooverwatch': '/overwatch',
            'fostarcraft': '/starcraft',
            'fostarcraft2': '/starcraft2',
            'fowarcraft': '/warcraft',
        }[code]

    @deprecated('APISite.version()')
    def version(self, code):
        return {
            'commons': u'1.28.2',
            'counterstrike': u'1.28.2',
            'dota2': u'1.28.2',
            'hearthstone': u'1.28.2',
            'heroes': u'1.28.2',
            'overwatch': u'1.28.2',
            'smash': u'1.28.2',
            'staff': u'1.28.2',
            'starcraft': u'1.28.2',
            'starcraft2': u'1.28.2',
            'warcraft': u'1.28.2',
            'fighters': u'1.28.2',
            'rocketleague': u'1.28.2',
            'clashroyale': u'1.28.2',
            'crossfire': u'1.28.2',
            'trackmania': u'1.28.2',
            'battlerite': u'1.28.2',
            'diabotical': u'1.28.2',
            'teamfortress': u'1.28.2',
            'leagueoflegends': u'1.28.2',
            'worldofwarcraft': u'1.28.2',
            'fifa': u'1.28.2',
            'pokemon': u'1.28.2',
            'projectx': u'1.28.2',
            'quake': u'1.28.2',
            'rainbowsix': u'1.28.2',
            'focommons': u'1.28.2',
            'fodota2': u'1.28.2',
            'fooverwatch': u'1.28.2',
            'fostarcraft': u'1.28.2',
            'fostarcraft2': u'1.28.2',
            'fowarcraft': u'1.28.2',
        }[code]

    def protocol(self, code):
        return {
            'commons': u'http',
            'counterstrike': u'http',
            'dota2': u'http',
            'hearthstone': u'http',
            'heroes': u'http',
            'overwatch': u'http',
            'smash': u'http',
            'staff': u'http',
            'starcraft': u'http',
            'starcraft2': u'http',
            'warcraft': u'http',
            'fighters': u'http',
            'rocketleague': u'http',
            'clashroyale': u'http',
            'crossfire': u'http',
            'trackmania': u'http',
            'battlerite': u'http',
            'diabotical': u'http',
            'teamfortress': u'http',
            'leagueoflegends': u'http',
            'worldofwarcraft': u'http',
            'fifa': u'http',
            'pokemon': u'http',
            'projectx': u'http',
            'quake': u'http',
            'rainbowsix': u'http',
            'focommons': u'http',
            'fodota2': u'http',
            'fooverwatch': u'http',
            'fostarcraft': u'http',
            'fostarcraft2': u'http',
            'fowarcraft': u'http',
        }[code]
